services:
  - type: web
    name: society-management-backend

    runtime: docker
    
    dockerfilePath: Dockerfile
    
    envVars:
      - key: PORT
        value: "8080"

      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://db.pximtggqmohthllmud.supabase.co:5432/postgres"
      - key: SPRING_DATASOURCE_USERNAME
        value: "postgres"
      - key: SPRING_DATASOURCE_PASSWORD
        value: "Ramyy.17"